name: main

on: [push, pull_request]

jobs:
  main:
    uses: Tyrrrz/.github/.github/workflows/nuget.yml@master
    with:
      dotnet-version: 7.0.x
      windows-only: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
